//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AOIEditVer3.rc
//
#define IDC_PAGER_CTRL                  2
#define IDD_MFCBEAUTY_FORM              3
#define IDR_TESTTREE_TOOLS              4
#define IDD_TESTREE_VIEW                5
#define IDC_BTN_OPER                    99
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_NEXTFORM                    101
#define IDD_DIALOG_PROSET_BASE          106
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_LOGO_TEXT                   124
#define IDS_RIBBON_HEXT                 125
#define IDS_RIBBON_OPER                 126
#define IDS_OPER_OPEN                   127
#define IDR_MAINFRAME                   128
#define IDR_1MAINFRAME                  128
#define IDR_MAINFRAME_256               129
#define IDS_OPER_CFG                    129
#define IDR_AOIEditVer3TYPE             130
#define IDS_LOGO                        130
#define ID_WINDOW_MANAGER               131
#define IDS_USER                        131
#define IDS_WINDOWS_MANAGER             132
#define IDS_OPER_RUN                    132
#define ID_VIEW_FILEVIEW                133
#define IDS_OPER_STOP                   133
#define ID_VIEW_CLASSVIEW               134
#define IDS_OPER_PAUSE                  134
#define ID_PROPERTIES                   135
#define IDS_RIBBON_DISP                 135
#define ID_OPEN                         136
#define IDS_DISP_SHOT                   136
#define ID_OPEN_WITH                    137
#define IDS_DISP_CONTIN                 137
#define ID_DUMMY_COMPILE                138
#define IDS_OPER_OPEN_DESC              138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define IDS_DISP_SAVE                   139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define IDS_BTN_SAVESYS                 140
#define ID_CLASS_DEFINITION             141
#define IDS_BTN_OPENCFG                 141
#define ID_CLASS_PROPERTIES             142
#define IDS_BTN_ERR_IMG                 142
#define ID_NEW_FOLDER                   143
#define IDS_DISP_ZERO                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTY_ADD_BTN             152
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_LIGHT_CTRL_WND_TITLE        159
#define IDS_LIGHT_CTRL_WND_TITLE_ENG    160
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_TESTLIST_TOOLBAR            185
#define IDS_OPER_CFG_ENG                186
#define IDS_OPER_RUN_ENG                187
#define IDS_OPER_STOP_ENG               188
#define IDS_OPER_PAUSE_ENG              189
#define IDS_RIBBON_DISP_ENG             190
#define IDS_DISP_SHOT_ENG               191
#define IDS_DISP_CONTIN_ENG             192
#define IDS_OPER_OPEN_DESC_ENG          193
#define IDS_DISP_SAVE_ENG               194
#define IDS_BTN_SAVESYS_ENG             195
#define IDS_BTN_OPENCFG_ENG             196
#define IDS_BTN_ERR_IMG_ENG             197
#define IDS_DISP_ZERO_ENG               198
#define IDS_USER_ENG                    199
#define IDB_QUESTION                    201
#define AFX_IDS_IDLEMESSAGE_ENG         202
#define ID_APP_ABOUT_ENG                203
#define ID_APP_EXIT_ENG                 204
#define AFX_IDS_SCCLOSE_ENG             205
#define AFX_IDS_SCRESTORE_ENG           206
#define AFX_IDS_SCTASKLIST_ENG          207
#define IDS_STATUS_PANE1_ENG            208
#define IDS_RIBBON_HEXT_ENG             209
#define IDS_RIBBON_OPER_ENG             210
#define IDS_OPER_OPEN_ENG               211
#define IDB_OBJECTFOLDER                214
#define IDS_ABOUT_TITLE_ENG             215
#define IDS_ABOUT_VESRION_ENG           216
#define IDS_ABOUT_TITLE                 217
#define IDS_ABOUT_VESRION               218
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDS_FILE_VIEW_ENG               222
#define IDS_CLASS_VIEW_ENG              223
#define IDS_OUTPUT_WND_ENG              224
#define IDS_PROPERTIES_WND_ENG          225
#define IDS_RIBBON_EXIT_ENG             226
#define IDS_RIBBON_HOME_ENG             227
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_CAPTION_BUTTON_ENG          236
#define IDS_CAPTION_BUTTON_TIP_ENG      237
#define IDS_CAPTION_IMAGE_TIP_ENG       238
#define IDS_CAPTION_IMAGE_TEXT_ENG      240
#define IDS_EXPLORER_ENG                241
#define IDS_EDIT_MENU_ENG               242
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_FILE_ENG             261
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_CAPTIONBAR           295
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDI_CURS                        311
#define IDI_ICON2                       312
#define IDB_OPERLARGE                   313
#define IDB_OPERSMALL                   314
#define IDR_POPUP_TESTTREE              315
#define IDB_TESTTREE_TOOLS_24           316
#define IDD_DIALOG_CHMODE               316
#define IDB_TESTTREE_VIEW               317
#define IDD_DIALOG_OPENPRO              317
#define IDB_TESTTREE_VIEW_24            318
#define IDD_DIALOG_PROSETTING           318
#define IDB_BITMAP_PRO_BUTTON           319
#define IDB_BITMAP_CREATE_BUTTON        320
#define IDB_BITMAP_LOAD_BUTTON          321
#define IDB_TESTLIST_TOOLBAR_HC         322
#define IDD_DISPS                       324
#define IDR_TESTTREE_TL                 324
#define IDD_DIALOG_SAVEPRO              325
#define IDR_OUT_EDIT                    326
#define IDB_BITMAP_UAC_BKGRD            330
#define IDB_BITMAP2                     331
#define IDB_BITMAP4                     333
#define IDB_BITMAP_PANEL                335
#define IDB_ACCEPT                      336
#define IDD_DIALOG_PROSET_CAMERA        338
#define IDD_DIALOG_PROSET_REJECT        339
#define IDB_PNG2                        339
#define IDB_DENY                        339
#define IDD_DIALOG_DRAW_SHAPE           342
#define IDD_DIALOG_SHOWDATA             344
#define IDD_HOMEVIEW                    345
#define IDS_RIBBON_OPEN_ENG             346
#define IDS_RIBBON_SAVE_ENG             347
#define IDS_RIBBON_SAVEAS_ENG           348
#define ID_VIEW_LIGHT_CTRL_WND          500
#define IDC_SCROLLBAR1                  1000
#define IDC_BUTTON_SCAN                 1001
#define IDC_COMBO_SOURE                 1002
#define IDC_WND1                        1003
#define IDC_WND2                        1004
#define IDC_WND3                        1005
#define IDC_WND4                        1006
#define IDC_WND5                        1007
#define IDC_WND6                        1008
#define IDC_WND7                        1009
#define IDC_WND8                        1010
#define IDC_EDIT_REJECTPORT             1011
#define IDC_WND9                        1011
#define IDC_EDIT_SIGNELTIME             1012
#define IDC_WND10                       1012
#define IDC_WND11                       1013
#define IDC_CHECK_REJECT                1014
#define IDC_WND12                       1014
#define IDC_EDIT_DELAYTIME              1015
#define IDC_BUTTON_SOURCESEL            1015
#define IDC_WND13                       1015
#define IDC_EDIT_NGCOUNT                1016
#define IDC_WND14                       1016
#define IDC_EDIT_WINNERPORT             1017
#define IDC_BUTTON1                     1017
#define IDC_WND15                       1017
#define IDC_EDIT_STATEPORT              1018
#define IDC_LIST_PROGRAM                1018
#define IDC_VERSION_TEXT                1018
#define IDC_WND16                       1018
#define IDC_STATIC_NAME                 1019
#define IDC_WND17                       1019
#define IDC_EDIT_CAMERAGAIN             1020
#define IDC_WND18                       1020
#define IDC_STATIC_SAVEDLG_LOGO         1021
#define IDC_STATIC_GAIN                 1021
#define IDC_WND19                       1021
#define IDC_MFCBUTTON1                  1022
#define IDC_WND20                       1022
#define IDC_EDIT_CAMERAGAIN2            1022
#define IDC_EDIT_CAMERATRIGERDELAY      1022
#define IDC_STATIC_OPENDLG_LOGO         1023
#define IDC_STATIC_IMG_CANCEL           1023
#define IDC_STATIC_GAIN2                1023
#define IDC_STATIC_OK                   1024
#define IDC_CHECK_TRIGGER               1025
#define IDC_STATIC_IMG_SOURCE           1025
#define IDC_CHECK_AUTOINIT              1026
#define IDC_CHECK_SAVE_IMAGE            1026
#define IDC_STATIC_IMG_SETTING          1027
#define IDC_STATIC_ERR_IMG_COUNT        1028
#define IDC_TAB_PROSETTING              1029
#define IDC_CHECK1                      1029
#define IDC_CHECK_CONNECT_LIGHT_CTRL    1029
#define IDC_EDIT_HEIGHT_PER_FRAME       1030
#define IDC_EDIT_LINE_PER_FRAME         1030
#define IDC_EDIT_FRAME_PER_SHEET        1031
#define IDC_BUTTON_DRAW_CIRCLE          1035
#define IDC_BTNQUERY                    1035
#define IDC_BUTTON_DRAW_RECTANGLE       1036
#define IDC_BUTTON_DRAW_POLYGON         1037
#define IDC_BUTTON_DRAW_ELLIPSE         1038
#define IDC_EDIT_TIME                   1038
#define IDC_EDIT_ERRORCOUNT             1038
#define IDC_RADIO1                      1039
#define IDC_EDIT_USERPASSWORD           1039
#define IDC_RADIO2                      1040
#define IDC_EDIT_USERGROUP              1040
#define IDC_EDIT_USERNAME               1041
#define IDC_RADIO_FILE                  1042
#define IDC_RADIO_FILES                 1043
#define IDC_RADIO_CAMERA                1045
#define IDC_STATIC_PATH                 1046
#define IDC_EDIT_TIMEI                  1047
#define IDC_COMBO_TraggerEdge           1048
#define IDC_CHECK2                      1050
#define IDC_LIST1                       1052
#define IDC_BUTTON_UNION                1053
#define IDC_BUTTON_DIFF                 1054
#define IDC_BUTTON_SAVE                 1055
#define IDC_BUTTON_REDRAW               1056
#define IDC_STATIC_TRIGERDELAY			1057
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772
#define ID_BTN_TESTTREE_OPEN            32773
#define ID_TESTLIST_BT_MOVE_DOWN        32774
#define ID_OPERATOR_32775               32775
#define ID_Menu                         32776
#define ID_OPERATOR_32777               32777
#define ID_32778                        32778
#define ID_FULL_SCREEN                  32779
#define ID_Menu32780                    32780
#define ID_END_FULLSCR                  32781
#define ID_ITEMEDIT_ONITEMUP            32785
#define OnItemUp                        32786
#define ID_ITEMEDIT_32787               32787
#define ID_BUTTON_TESTTREE_OPEN         32788
#define OnItemDown                      32788
#define ID_ITEM_DOWN                    32789
#define ID_ITEM_UP                      32790
#define ID_Menu32791                    32791
#define ID_TESTLIST_BT_DELETE           32792
#define ID_ITEM_MOVE                    32792
#define ID_TESTLIST_BT_MOVE_UP          32793
#define ID_TESTLIST_BT_APPLY            32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        340
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           325
#endif
#endif
