//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SLACMVSN.rc
//
#define IDS_IDS_ProshTitle              97
#define IDS_OBJECT_PROPERTIES           98
#define IDP_OLE_INIT_FAILED             99
#define IDD_ABOUTBOX                    100
#define IDD_SLACMVSN_FORM               101
#define IDD_PROPPAGE_OVERVIEWPAGE       107
#define IDD_PROPPAGE_CHANGEL            108
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_SLACMVSNTYPE                130
#define IDS_EDIT_MENU                   306
#define IDB_BITMAP_LOG                  310
#define IDB_BITMAP1                     311
#define IDB_EXIT                        311
#define IDB_EXIT_IN                     312
#define IDB_HELP                        313
#define IDB_HELP_IN                     314
#define IDB_USER                        315
#define IDB_USER_IN                     316
#define IDR_MENU_MYKV                   320
#define IDI_ICON1                       321
#define IDD_DIALOG_LOGIN                324
#define IDB_BITMAP_OFFLINEUP            325
#define IDD_GROUP                       325
#define IDD_USERMANAGER                 330
#define IDB_BITMAP_PRONAMEUP            334
#define IDB_BITMAP_PRONAMEDOWN          335
#define IDB_BITMAP_OFFLINEDISABLE       340
#define IDB_BITMAP_ONLINEUP1            341
#define IDB_STATEICONS                  344
#define IDD_DIALOG_SHOWDATA             345
#define IDB_PNG1                        346
#define IDB_LOGIN                       352
#define IDB_LOGIN1                      353
#define IDB_BITMAP_WARNING              356
#define IDD_DIALOG_WARNING              358
#define IDB_PNG_WARNING                 360
#define IDB_PNG_ALARM                   361
#define IDB_PNG_PAUSE                   362
#define IDB_PNG_READY                   363
#define IDB_PNG_RUN                     364
#define IDB_PNG_STOP                    365
#define IDB_BITMAP_LOGOUT               366
#define IDB_BITMAP_LOGOUT_IN            367
#define IDB_PNG3                        369
#define IDB_BITMAP2                     370
#define IDC_USER_MANAGER_DISABLE        370
#define IDI_ICON3                       372
#define IDB_BITMAP3                     373
#define IDB_BITMAP_EXIT_DISABLE         373
#define IDC_STATIC_OVERVIEW             1000
#define IDC_BUTTON1                     1001
#define IDC_BTN_OFFLINE                 1001
#define IDC_BUTTON_CREATE               1001
#define IDC_TAB_M                       1002
#define IDC_TAB_MAIN                    1002
#define IDC_BTN_ONLINE                  1002
#define IDC_STATIC_CUSTOMINFO           1003
#define IDC_EXIT                        1004
#define IDC_STATIC_CUSTOMINFO2          1006
#define IDC_STATIC_T                    1006
#define IDC_BUT_LOGIN                   1007
#define IDC_GROUPINFO                   1008
#define IDC_BUT_LOGIN2                  1008
#define IDC_BUT_LOGOUT                  1008
#define IDC_BTN_LOAD                    1010
#define IDC_BTN_NOPIC                   1011
#define IDC_BTN_OKPIC                   1012
#define IDC_BUTTON4                     1013
#define IDC_BTN_OPEN                    1013
#define IDC_BTN_PRONAME                 1014
#define IDC_BTN_MENU                    1014
#define IDC_COMBO1                      1017
#define IDC_COMBO_WARNING               1017
#define IDC_COMBO_GROUP                 1017
#define IDC_TOTALNUM                    1018
#define IDC_FAUTYNUM                    1019
#define IDC_OKNUM                       1020
#define IDC_NAME                        1021
#define IDC_USERNAME_GROUP              1022
#define IDC_PSW                         1022
#define IDC_STATIC_01                   1023
#define IDC_STATIC_02                   1024
#define IDC_STATIC_03                   1025
#define IDC_STATUS                      1027
#define IDC_COMBO2                      1028
#define IDC_ID                          1028
#define IDC_LIST1                       1029
#define IDC_STATIC_LOGPIC               1030
#define IDC_ROLE                        1034
#define IDC_EDIT_Operator               1034
#define IDC_USER                        1035
#define IDC_EDIT_Password               1035
#define IDC_GROUPID                     1035
#define IDC_GROUPDES                    1036
#define IDC_GROUPNAME                   1037
#define DC_LISTVIEW1                    1041
#define IDC_USERINFO                    1042
#define IDC_DELETE                      1044
#define IDC_MODIFICATION                1045
#define IDC_BTN_QUERY                   1046
#define IDC_DATETIMEPICKER1             1047
#define IDC_DATETIMEPICKER2             1048
#define IDC_DATETIMEPICKER3             1049
#define IDC_DATETIMEPICKER4             1050
#define IDC_STATIC_ALL                  1051
#define IDC_STATIC_FAIL                 1052
#define IDC_STATIC_PERC                 1053
#define IDC_BUTTON3                     1053
#define IDC_BT_WARNING                  1053
#define ID_32771                        32771
#define ID_32772                        32772
#define IDD_DIALOG_USERMODE             32773
#define IDC_USERID                      32774
#define IDC_PSWD                        32775
#define IDL_ITEM                        32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        374
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
